### ISSUE TITLE
Request to adapt to Chinese, Japanese and Korean 🙏

### ISSUE THREAD

**Issue by aka-phrankie** [mlava/word-count#1]
Subject: Request for Adaptation of Word Count Extension for Chinese, Japanese, and Korean Text

Dear Developer,

I hope this message finds you well. I am a user of the Word Count extension for Roam Research, and I have encountered an issue with the current functionality. The extension seems to skip the word count for non-English text, particularly Chinese, Japanese, and Korean.

Given that Roam Research users may have content in various languages, including Chinese, Japanese, and Korean, it would be immensely beneficial if the Word Count extension could accurately count the words in these languages as well.

Therefore, I kindly request an adaptation of the extension to ensure that it accurately counts the words in Chinese, Japanese, and Korean text, in addition to English.

Thank you for your attention to this matter, and I look forward to the potential adaptation of the extension.

Of course, if you are still using Roam Research.🤯

**Comment by mlava** [comment]
Hi @aka-phrankie 
Sorry for the delay, I've been offline for a period...
Can you tell me how words are counted in Chinese, Japanese, and Korean? Is each Ideograph a 'word'. Is it the same in each of those languages?

**Comment by aka-phrankie** [comment]
Yes, it is usually like this.
This is some explanations， https://devv.ai/zh/search?threadId=d9zsn1o9uxvk
This is some implementation methods， https://devv.ai/zh/search?threadId=d9zskodznxfk
Of course, the link of human actual solutions on the right side of the link may be better

**Comment by mlava** [comment]
This has now been implemented, but you will need to wait for the Roam team to review and approve the PR.
Thanks for the suggestion!

https://github.com/Roam-Research/roam-depot/pull/855

**Comment by mlava** [comment]
This PR has been approved and the new version is available. Cheers!
